server:
  jetty:
    threads:
      min: 20
      max: 20
  port: 12000
spring:
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      maximum-pool-size: 5
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://127.0.0.1:11050/${spring.application.name}
    username: postgres
    password: pwd
client:
  max-total-connections: 2000
  default-max-per-route: 2000
  paze:
    url: https://app-demo.paze.eu/api/v1/
#    bearer-token: SECRET
application-base-url: http://localhost:${server.port}