spring:
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      maximum-pool-size: 5
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://127.0.0.1:11050/${spring.application.name}
    username: postgres
    password: pwd
wiremock:
  server:
    port: 8084
client:
  max-total-connections: 2000
  default-max-per-route: 2000
  paze:
    url: http://localhost:${wiremock.server.port}/paze/
    bearer-token: token
application-base-url: http://localhost:${server.port}